  <section id="dna">
            <div id="one">&#9899;</div>
            <div id="onex">&#9899;</div>
            <div id="two">&#9899;</div>
            <div id="twox">&#9899;</div>
            <div id="three">&#9899;</div>
            <div id="four">&#9899;</div>
            <div id="five">&#9899;</div>
            <div id="six">&#9899;</div>
            <div id="threex">&#9899;</div>
            <div id="fourx">&#9899;</div>
            <div id="fivex">&#9899;</div>
            <div id="sixx">&#9899;</div>
            <div id="seven">&#9899;</div>
            <div id="sevenx">&#9899;</div>
            <div id="eight">&#9899;</div>
            <div id="eightx">&#9899;</div>
            <div id="nine">&#9899;</div>
            <div id="ninex">&#9899;</div>
            <div id="ten">&#9899;</div>
            <div id="tenx">&#9899;</div>
            <div id="eleven">&#9899;</div>
            <div id="elevenx">&#9899;</div>
            <div id="twelve">&#9899;</div>
            <div id="twelvex">&#9899;</div>
            <div id="thirt">&#9899;</div>
            <div id="thirtx">&#9899;</div>
            <div id="fourt">&#9899;</div>
            <div id="fourtx">&#9899;</div>
            <p class="animated fadeIn"><span>Dandole <br> Vida <br> a tus Diseños</span></p>
        </section>
     